// ============================================================
// CARD DEFINITIONS — pure data, no callbacks
// Abilities (callbacks, passives, special props) are in abilities.js
// and merged at the bottom of this file.
//
// See card-text-audit.md for the canonical terminology glossary.
// Key rules:
//   - Keywords in the abilities[] array render as badges. NEVER repeat them in desc.
//   - Numeric formats: (X/Y) for summons, (+X/+Y) buffs, (−X/−Y) debuffs with real minus sign.
//   - Canonical triggers: When Played: / When Destroyed: / When Discarded: / When Damaged:
//     / Start of Tricks: / Start of Tricks (once): / Each Turn: / While Active: / Jump:
//   - Canonical targets: an enemy / the enemy opposite / an adjacent enemy / all enemies
//     / a random enemy / an enemy with ≤ N ATK (use ≤, not "or less")
//   - Splash N as a one-shot verb is allowed in desc (Xenomorph on-death etc.);
//     as a persistent attribute it belongs in the abilities array instead.
// ============================================================

const CARD_DEFS = [
  // ==================== COST 1 ====================
  { name: "Ant-Man", cost: 1, attack: 2, health: 1, type: "hero",
    abilities: [],
    desc: "When Played: Summon a (1/1) Ant with Bullseye in any lane. Destroy an enemy with ≤ 1 ATK or ≤ 1 HP." },
  { name: "Poison Ivy", cost: 1, attack: 1, health: 3, type: "villain",
    abilities: [],
    desc: "Each Turn: Charm a random ally — Poison Ivy gains ATK equal to that ally's ATK for this turn (lost if the charmed ally dies)." },
  { name: "King Shark", cost: 1, attack: 3, health: 3, type: "villain",
    abilities: ["Overdrive"],
    desc: "" },
  { name: "Black Widow", cost: 1, attack: 2, health: 1, type: "hero",
    abilities: ["Bullseye", "Evade 1"],
    desc: "When Played: Freeze 1 an adjacent enemy." },
  { name: "Man-Bat", cost: 1, attack: 1, health: 3, type: "villain",
    abilities: ["Bullseye"],
    desc: "Start of Tricks: Move to an empty lane. The enemy opposite takes (−1/−1)." },
  { name: "Harley Quinn", cost: 1, attack: 0, health: 1, type: "villain",
    abilities: ["Crazy", "Splash 1"],
    desc: "When Played: Both players draw a card. While Active: Deals 1 damage to your HP before attacking." },
  { name: "Gorilla Grodd", cost: 1, attack: 2, health: 3, type: "villain",
    abilities: [],
    desc: "When Played: Mind Control 1 an enemy with cost ≤ 3. You choose which of its own allies it attacks this turn." },
  { name: "Hawkeye", cost: 1, attack: 1, health: 2, type: "hero",
    abilities: ["Bullseye"],
    desc: "When Played: Splash 1. While Active: Splash damage from allies also removes 1 ATK." },
  { name: "Mr. Fantastic", cost: 1, attack: 0, health: 0, type: "hero",
    abilities: ["Draw 1"],
    desc: "When Discarded: The next 2 cards you draw cost 1 less." },
  { name: "Mr. Freeze", cost: 1, attack: 2, health: 3, type: "villain",
    abilities: [],
    desc: "When Played: Freeze 1 the enemy opposite. Freeze your HP bar — the next hit to it is negated." },
  { name: "Sabertooth", cost: 1, attack: 2, health: 3, type: "villain",
    abilities: [],
    desc: "While Active: Add (+1/+1) when dealing damage to the opponent's HP." },
  { name: "Xenomorph", cost: 2, attack: 0, health: 1, type: "villain",
    abilities: [],
    desc: "While Active: Add (+1/+1) for each card played (not summoned). When Destroyed: Splash 1." },

  // ==================== COST 2 ====================
  { name: "Bane", cost: 2, attack: 2, health: 3, type: "villain",
    abilities: ["Overdrive"],
    desc: "When Played: Give an enemy (−1/−1) and remove all Evade. While Active: Add (+1/+1) when damaged." },
  { name: "Catwoman", cost: 1, attack: 1, health: 1, type: "villain",
    abilities: ["Bullseye", "Evade 1"],
    desc: "When Played: Steal 1 Energy from the opponent next turn." },
  { name: "Spawn", cost: 2, attack: 3, health: 3, type: "villain",
    abilities: ["Bullseye", "Overdrive"],
    desc: "" },
  { name: "Dr. Strange", cost: 2, attack: 2, health: 1, type: "hero",
    abilities: ["Untrickable", "Evade 1"],
    desc: "When Played: Next draw phase, peek at the top 2 cards — keep one, the other goes to the opponent. While Active: Adjacent allies gain Untrickable." },
  { name: "Gamora", cost: 2, attack: 2, health: 3, type: "hero",
    abilities: [],
    desc: "When Played: Destroy an enemy with ≤ 2 HP. While Active: Add (+1/+1) when destroying an enemy." },
  { name: "Ghostface", cost: 2, attack: 2, health: 1, type: "villain",
    abilities: ["Bullseye"],
    desc: "Jump: When the enemy plays a Trick, Ghostface glows — play for free. When Played: Summon a (2/1) Ghostface with Bullseye in any lane." },
  { name: "Human Torch", cost: 2, attack: 2, health: 3, type: "hero",
    abilities: [],
    desc: "When Played: Splash 1 to the enemy lane and deal 2 damage to an enemy." },
  { name: "Invisible Woman", cost: 1, attack: 1, health: 1, type: "hero",
    abilities: ["Evade 1"],
    desc: "When Played: Give an ally Evade 1 for 1 turn. While Active: You can play cards face-down; they're immune to everything until revealed before Tricks." },
  { name: "Jango Fett", cost: 2, attack: 2, health: 4, type: "villain",
    abilities: ["Armor 1", "Hunt"],
    desc: "While Active: Splash 1 when moving to a new lane." },
  { name: "Juggernaut", cost: 2, attack: 2, health: 4, type: "hero",
    abilities: ["Bullseye", "Armor 1", "Immunity"],
    desc: "While Active: Adjacent allies gain Immunity 1." },
  { name: "Nightwing", cost: 2, attack: 3, health: 1, type: "hero",
    abilities: ["Evade 1"],
    desc: "When Played: Remove 2 ATK from an enemy." },
  { name: "Peacemaker", cost: 2, attack: 2, health: 3, type: "hero",
    abilities: [],
    desc: "When Played: Destroy an enemy with ≤ 2 ATK. While Active: Add (+1/+1) when destroying an enemy." },
  { name: "Rocket Raccoon", cost: 2, attack: 2, health: 1, type: "hero",
    abilities: [],
    desc: "When Played: Deal 4 damage to an enemy." },
  { name: "Sandman", cost: 2, attack: 3, health: 3, type: "villain",
    abilities: [],
    desc: "While Active: Enemy Tricks cost 1 more Energy." },
  { name: "The Flash", cost: 2, attack: 2, health: 1, type: "hero",
    abilities: ["Invincible 2"],
    desc: "When Played: Freeze 1 an adjacent enemy. Choose who plays first next turn." },
  { name: "The Thing", cost: 2, attack: 3, health: 2, type: "hero",
    abilities: ["Armor 2"],
    desc: "" },

  // ==================== COST 3 ====================
  { name: "Ahsoka", cost: 3, attack: 2, health: 2, type: "hero",
    abilities: ["Evade 1", "Draw 1"],
    desc: "While Active: Bonus attack each time an ally is destroyed." },
  { name: "Carnage", cost: 3, attack: 3, health: 4, type: "villain",
    abilities: ["Overdrive"],
    desc: "Start of Tricks (once): Heal yourself for each enemy on board." },
  { name: "Deathstroke", cost: 3, attack: 3, health: 3, type: "villain",
    abilities: [],
    desc: "When Played: Destroy an enemy with ≤ 3 HP. While Active: Add (+1/+1) when destroying an enemy." },
  { name: "Dr. Octopus", cost: 3, attack: 2, health: 4, type: "villain",
    abilities: ["Splash 2"],
    desc: "While Active: Add 1 extra Energy each round." },
  { name: "Green Goblin", cost: 3, attack: 3, health: 3, type: "villain",
    abilities: [],
    desc: "When Played: Splash 1, then Splash 2. Start of Tricks: Move to an empty lane opposite an enemy and Splash 1." },
  { name: "Groot", cost: 3, attack: 3, health: 3, type: "hero",
    abilities: ["Armor 1", "Draw 1"],
    desc: "When Played: Give adjacent allies Damage Immunity for 1 turn." },
  { name: "Jigsaw", cost: 2, attack: 0, health: 0, type: "villain",
    abilities: [],
    desc: "When Discarded: Set up to 3 Bear Traps in empty enemy lanes — the first enemy to enter takes (−1/−1). Then drag an enemy to another empty lane." },
  { name: "Loki", cost: 3, attack: 2, health: 1, type: "villain",
    abilities: ["Evade 1"],
    desc: "When Played: Fill your Block Meter." },
  { name: "Moder", cost: 3, attack: 2, health: 2, type: "villain",
    abilities: [],
    desc: "When Played: The opponent's next card is forced into this lane. That card loses all abilities and keywords." },
  { name: "Red Skull", cost: 3, attack: 1, health: 4, type: "villain",
    abilities: [],
    desc: "When Played: Give an ally (+2/+2). While Active: Your cards can be played during the Trick Phase." },
  { name: "Scarlet Witch", cost: 3, attack: 0, health: 0, type: "hero",
    abilities: [],
    copiesOpposite: true,
    desc: "When Played: Copy the ATK and HP of the enemy directly opposite. (Her stat orbs read \"?\" until she lands.)" },
  { name: "Solomon Grundy", cost: 3, attack: 3, health: 6, type: "villain",
    abilities: [],
    desc: "When Destroyed: Draw a random card from the shared Dead Pile to your hand." },
  { name: "Star-Lord", cost: 3, attack: 2, health: 2, type: "hero",
    abilities: ["Taunt 1", "Evade 1"],
    desc: "When Played: Give an ally (+2/+2)." },
  { name: "Symbiote Spider-Man", cost: 3, attack: 3, health: 3, type: "hero",
    abilities: ["Evade 1"],
    desc: "When Played: Both players shuffle 2 cards back into the deck and draw 2. Heal yourself for 2." },
  { name: "Winter Soldier", cost: 3, attack: 3, health: 2, type: "villain",
    abilities: [],
    desc: "When Played: Destroy an enemy with ≤ 3 ATK. While Active: Add (+1/+1) when destroying an enemy." },

  // ==================== COST 4 ====================
  { name: "Anti-Venom", cost: 4, attack: 3, health: 5, type: "hero",
    abilities: [],
    desc: "When Played: Heal yourself for 4. Move an ally to another empty lane." },
  { name: "Black Panther", cost: 4, attack: 2, health: 3, type: "hero",
    abilities: ["Armor 1"],
    desc: "When Played: Play a card from your hand with cost ≤ 3 for free. While Active: Add (+1/+1) to each card you play." },
  { name: "Cyborg", cost: 5, attack: 3, health: 3, type: "hero",
    abilities: [],
    desc: "When Destroyed: Summon a random card from your hand in Cyborg's lane." },
  { name: "Deadpool", cost: 4, attack: 3, health: 4, type: "hero",
    abilities: [],
    desc: "When Destroyed: Swap a face-down card from the enemy's hand with one from yours." },
  { name: "Green Lantern", cost: 4, attack: 2, health: 4, type: "hero",
    abilities: [],
    desc: "While Active: Add extra Energy next turn equal to damage Green Lantern dealt this turn." },
  { name: "Jason Voorhees", cost: 4, attack: 2, health: 2, type: "villain",
    abilities: ["Hunt", "Overdrive", "Revive 1"],
    desc: "Jump: When any ally dies, Jason glows — play for free. When Destroyed: Revive as (3/4)." },
  { name: "Kang", cost: 4, attack: 2, health: 1, type: "villain",
    abilities: [],
    desc: "When Played: Peek at the top 2 draw pile cards. Keep one — its cost is permanently reduced by 2. If the new cost is ≤ 2, play it for free." },
  { name: "Martian Manhunter", cost: 4, attack: 4, health: 4, type: "hero",
    abilities: ["Evade 1"],
    desc: "When Played: Copy all abilities from a random Dead Pile card, then trigger its When Played effect." },
  { name: "Optimus Prime", cost: 4, attack: 4, health: 4, type: "hero",
    abilities: ["Armor 1"],
    desc: "When Played: An adjacent ally immediately attacks an enemy opposite or adjacent to Optimus Prime." },
  { name: "Predator", cost: 4, attack: 3, health: 4, type: "villain",
    abilities: ["Bullseye", "Evade 1", "Hunt"],
    desc: "When Played: Deal 3 damage to an enemy. While Active: Add (+1/+0) when destroying an enemy." },
  { name: "Darth Maul", cost: 4, attack: 4, health: 4, type: "villain",
    abilities: [],
    desc: "When Played: Draw a Trick; it costs 1 less. While Active: Add (+2/+0) for each Trick played by either player." },
  { name: "Raven", cost: 3, attack: 3, health: 4, type: "hero",
    abilities: [],
    desc: "When Played: Empty the opponent's Block Meter. Unfreeze and unstun all allies." },
  { name: "The Grinch", cost: 3, attack: 1, health: 2, type: "villain",
    abilities: [],
    desc: "When Played: Steal a Trick (opponent picks). Keep it (cost +1) or return it to triple The Grinch's stats. If opponent has no tricks, stats triple." },
  { name: "Venom", cost: 4, attack: 4, health: 6, type: "villain",
    abilities: [],
    desc: "When Played: Freeze 1 an enemy. Start of Tricks (once): Heal yourself for each ally on board." },
  { name: "Wolverine", cost: 4, attack: 2, health: 2, type: "hero",
    abilities: ["Revive 1"],
    desc: "While Active: Destroy any enemy with cost ≤ 7 that damages Wolverine. When Destroyed: Revive as (6/5) with Overdrive." },
  { name: "Wonder Woman", cost: 4, attack: 3, health: 3, type: "hero",
    abilities: ["Armor 1", "Unresistible"],
    desc: "When Played: Stun 1 the enemy opposite. Add 2 to your Block Meter. While Active: Your attack chains (ATK−1) to 1 adjacent enemy." },

  // ==================== COST 5 ====================
  { name: "Davy Jones", cost: 5, attack: 3, health: 6, type: "villain",
    abilities: [],
    desc: "When Played: Summon The Kraken (5/3) in any lane." },
  { name: "Captain America", cost: 5, attack: 3, health: 4, type: "hero",
    abilities: ["Armor 1"],
    desc: "When Played: Give an ally Invincible 1. While Active: All cards in your hand cost 1 less Energy." },
  { name: "Iron Man", cost: 5, attack: 4, health: 5, type: "hero",
    abilities: ["Armor 1"],
    desc: "Can be played during the Trick Phase. When Played: Destroy all damaged enemies with cost ≤ 8." },
  { name: "Joker", cost: 5, attack: 0, health: 5, type: "villain",
    abilities: ["Insane"],
    desc: "When Played: Fear 1 an enemy with cost ≤ 4. Start of Tricks: Applies Crazy to the highest-ATK enemy (always keeps a target on the board)." },
  { name: "Lex Luthor", cost: 5, attack: 2, health: 6, type: "villain",
    abilities: [],
    desc: "While Active: The opponent cannot draw cards or make bonus attacks. (Tricks can still be drawn.)" },
  { name: "Michael Myers", cost: 3, attack: 3, health: 4, type: "villain",
    abilities: ["Overdrive"],
    desc: "Jump: When the enemy plays a card costing less than Michael Myers, he glows — play for free." },
  { name: "Professor X", cost: 5, attack: 0, health: 0, type: "hero",
    abilities: [],
    desc: "When Discarded: Permanently convert an enemy with cost ≤ 4 to your team. Its abilities reactivate." },
  { name: "Red Hulk", cost: 5, attack: 4, health: 5, type: "hero",
    abilities: [],
    desc: "While Active: When damaged, add that damage to your Block Meter and Splash it back." },
  { name: "Spider-Man", cost: 5, attack: 4, health: 4, type: "hero",
    abilities: ["Evade 1", "Unresistible"],
    desc: "When Played: Freeze 1 an enemy. While Active: Add (+1/+1) when evading. 50% chance to regain a charge on evade." },
  { name: "The Batman Who Laughs", cost: 5, attack: 3, health: 3, type: "villain",
    abilities: [],
    desc: "When Played: The next card the enemy plays goes to your hand. Choose to keep it or destroy it for (+2/+2)." },
  { name: "General Grievous", cost: 5, attack: 4, health: 7, type: "villain",
    abilities: [],
    desc: "While Active: The opposing player cannot charge their Block Meter when hit." },

  // ==================== COST 6 ====================
  { name: "Hela", cost: 6, attack: 5, health: 6, type: "villain",
    abilities: [],
    desc: "When Played: Summon two (3/1) Undead Warriors. Draw a random card from the shared Dead Pile to your hand." },
  { name: "Homelander", cost: 4, attack: 4, health: 5, type: "villain",
    abilities: [],
    desc: "When Played: Choose to sacrifice an ally — either deal damage to an enemy equal to that ally's cost, or destroy an enemy with cost ≤ that ally's cost. (Skip if you'd rather not.)" },
  { name: "Hulk", cost: 6, attack: 4, health: 6, type: "hero",
    abilities: [],
    desc: "When Played: Deal 2 damage to all enemies. While Active: Splash equals Hulk's ATK. Add (+1/+1) when damaged." },
  { name: "Magneto", cost: 6, attack: 4, health: 6, type: "villain",
    abilities: [],
    desc: "When Played: Choose lanes for the opponent's next 2 card placements. While Active: Enemy cards in even lanes take (−1/−2)." },
  { name: "Obi-Wan", cost: 6, attack: 4, health: 8, type: "hero",
    abilities: ["Taunt 99"],
    desc: "While Active: Damage from enemies in other lanes reflects back. The enemy directly opposite is exempt. When Destroyed: The enemy opposite loses all ATK this combat." },
  { name: "Ultron", cost: 6, attack: 5, health: 3, type: "villain",
    abilities: [],
    desc: "When Destroyed: Summon 2 (5/3) Ultron copies in the lowest and highest empty lanes. Copies don't trigger this effect." },

  // ==================== COST 7 ====================
  { name: "Dr. Doom", cost: 7, attack: 5, health: 5, type: "villain",
    abilities: [],
    desc: "When Played: Return a card from your Dead Pile (cost ≤ 9) to your hand with its cost permanently reduced by 3. Summon a (5/5) Doombot." },
  { name: "Gojo", cost: 7, attack: 6, health: 6, type: "hero",
    abilities: ["Immunity", "Invincible 1"],
    desc: "When Played: Move an enemy to another empty lane. Zero ATK on enemies in a 3-lane cone for 1 turn. After 2 combats: destroy all enemies in the opposite-parity lanes." },
  { name: "Gorr", cost: 7, attack: 4, health: 8, type: "villain",
    abilities: ["Evade 1", "Immunity"],
    desc: "When Played: Devour the highest-cost card from each player's hand. Summon a random card (cost 2-9) in any lane." },
  { name: "Mahoraga", cost: 7, attack: 7, health: 7, type: "villain",
    abilities: ["Revive 1"],
    desc: "While Active: Absorb all damage that would hit your HP. When Destroyed: Revive as (7/9) with Armor 1 and Immunity 1." },
  { name: "Omni-Man", cost: 7, attack: 4, health: 8, type: "villain",
    abilities: ["Overdrive"],
    desc: "When Played: Deal 3 damage to all enemies. Start of Tricks: Move to another empty lane. While Active: Add 1 to your Block Meter for each enemy destroyed." },
  { name: "Silver Surfer", cost: 7, attack: 7, health: 7, type: "hero",
    abilities: [],
    desc: "When Played: Remove 3 ATK from an enemy. While Active: Enemy cards cost 1 more Energy. (Tricks unaffected.)" },
  { name: "Revan", cost: 7, attack: 6, health: 8, type: "villain",
    abilities: [],
    desc: "When Played: Give another ally Revive 1." },

  // ==================== COST 8 ====================
  { name: "Darth Vader", cost: 8, attack: 6, health: 7, type: "villain",
    abilities: ["Armor 1", "Unresistible 1"],
    desc: "When Played: Move an enemy to an empty lane. Fear 1 an enemy. Then start a 7-damage chain — pick direction each step; damage decreases by 1 per hit." },
  { name: "Emperor Palpatine", cost: 8, attack: 6, health: 8, type: "villain",
    abilities: ["Unresistible"],
    desc: "When Played: Chain Freeze 1 consecutive enemies. While Active: Frozen enemies take double damage." },
  { name: "Luke Skywalker", cost: 8, attack: 5, health: 6, type: "hero",
    abilities: ["Unresistible"],
    desc: "When Played: Mind Control 1 an enemy. While Active: All allies get (+1/+1) and all enemies get (−1/−1)." },
  { name: "Thor", cost: 8, attack: 7, health: 7, type: "hero",
    abilities: ["Splash 5", "Unresistible"],
    desc: "When Played: Choose an enemy to Freeze 1, then Splash 5. Start of Tricks: Freeze 1 a random unfrozen enemy." },
  { name: "Yoda", cost: 8, attack: 4, health: 5, type: "hero",
    abilities: ["Immunity"],
    desc: "When Played: Add (+4/+4) to an ally. If no allies, add (+2/+3) to self and cleanse all debuffs on every ally." },

  // ==================== COST 9 ====================
  { name: "Batman", cost: 9, attack: 7, health: 5, type: "hero",
    abilities: ["Evade 2", "Unresistible"],
    desc: "When Played: Lock the highest-cost card the opponent can play next turn. Fear 1 any enemy, then throw Batarangs." },
  { name: "Darkseid", cost: 9, attack: 6, health: 9, type: "villain",
    abilities: ["Immunity"],
    desc: "When Played: Summon a (2/1) Parademon. Collapse any number of contested odd or even lanes for 3 rounds (not Darkseid's lane). While Active: Divide Darkseid's ATK among all enemies." },
  { name: "Superman", cost: 9, attack: 8, health: 8, type: "hero",
    abilities: ["Immunity", "Unresistible"],
    desc: "When Played: Strike the enemy opposite immediately (or the opponent's HP if the lane is empty). Choose two enemies to Freeze 1. Deal 5 damage to an enemy." },
  { name: "Thanos", cost: 9, attack: 6, health: 9, type: "villain",
    abilities: [],
    desc: "Can be played during the Trick Phase. When Played: Destroy enemies in 3 random lanes (no duplicates)." },

  // ==================== COST 10 ====================
  { name: "Anakin Skywalker", cost: 10, attack: 7, health: 9, type: "hero",
    abilities: ["Immunity", "Invincible 1", "Unresistible 1", "Draw 1"],
    desc: "When Played: Draw 1. Fear 1 an enemy. Start of Tricks (once): Move to an open lane and do a bonus attack. While Active: When an ally is destroyed, Anakin does a bonus attack." },
  { name: "Dormammu", cost: 10, attack: 3, health: 3, type: "villain",
    abilities: ["Immunity", "Invincible 1", "Unresistible 3", "Draw 1"],
    desc: "When Played: Gain foresight for 2 draw phases — peek at the top 2 cards and keep one (the other goes to the opponent). Start of Tricks (once): Drain 3 enemies, leaving them as (0/1)." },
  { name: "Dr. Manhattan", cost: 10, attack: 8, health: 10, type: "hero",
    abilities: ["Immunity", "Invincible 1", "Taunt 1", "Draw 1"],
    desc: "When Played: Heal yourself for 5. While Active: Add 2 extra Energy each round." },
  { name: "Galactus", cost: 10, attack: 9, health: 11, type: "villain",
    abilities: ["Immunity", "Invincible 1", "Unresistible", "Draw 1"],
    desc: "Start of Tricks (once): Devour 2 enemies. Each Turn: Devour any enemy with ≤ 4 ATK." },
  { name: "Knull", cost: 10, attack: 7, health: 7, type: "villain",
    abilities: ["Immunity", "Invincible 1"],
    desc: "When Played: Summon a random card (cost 1-9) in each of your empty lanes." },
  { name: "Trigon", cost: 10, attack: 9, health: 8, type: "villain",
    abilities: ["Immunity", "Invincible 1", "Unresistible 3", "Draw 1"],
    desc: "When Played: Steal the opponent's Block Meter. Start of Tricks (once): Freeze 1 all enemies. While Active: When Trigon destroys an enemy, destroy another chained enemy." }
];

